[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "lumart"
version = "2.1.2"
description = "A high-fidelity image-to-terminal renderer written in Python."
readme = "README.md"
requires-python = ">=3.8"
license = { text = "AGPL-3.0" }
dependencies = [
    "Pillow>=10.0.0"
]

[project.scripts]
lumart = "lumart:main"
luma = "lumart:main"
